version: '3.2'

services:
  scala:
    build:
      context: ./
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
    networks:
      - scala-study
    ports:
      - "3000:3000"

networks:
  scala-study:
    external: true
